### ISSUE TITLE
Out of memory on 24 GB VRAM GPU

### ISSUE THREAD

**Issue by kpoeppel** [cvlab-columbia/zero123#12]
I had some trouble to debug it, but it seems like an OutOfMemory error, as 24.2 GB are filled via 'nvidia-smi', leading to a failure:
cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
or with cuDNN disabled:
cuBLAS error: CUBLAS_STATUS_NOT_INITIALIZED
in the F.conv2D call inside .

If you got it running on a RTX3090, could you share the configuration changes?
I used a 128x128 RBG image as a smallest test.

**Comment by ruoshiliu** [comment]
Hi @kpoeppel , which command/script are you running?

**Comment by kpoeppel** [comment]
I ran the `gradio_new.py` web-interface as suggested in `README.md`, as well as a adapted version to call the same functionality from cli for debugging. Also removed (for testing) the NSFW filter, to see if that lowers the memory footprint by enough to get it running.

**Comment by ruoshiliu** [comment]
I just ran the same command and it takes around 18 GB for 4 samples. When does the OOM error happen? Is it before or after the local / public URL appears in the CLI? Would be helpful if you can include a complete screenshot or the command and error message. Also which OS are you running on? We only tested on linux, for windows, you can refer to this issue: https://github.com/cvlab-columbia/zero123/issues/8#issuecomment-1479838642

**Comment by ruoshiliu** [comment]
How big is the input image? Have you try different images with smaller size? I just pushed a small fix. Could you pull and try again?

**Comment by kpoeppel** [comment]
Input image is 50 kB, 128x128 pixels, I think below that becomes non-sense.
It works now, with ~16.5 GiB VRAM usage, though I do not understand why these small changes made the difference!?
Essentially you just add some thumbnails?
Nevertheless, it works now, thanks a lot!

**Comment by ruoshiliu** [comment]
thumbnail is a pillow function to resize image before passing through the pipeline but I don't quite understand how 128x128 pixels could crash it as the thumbnail function upsamples it to 1536x1536. Anyways, glad it works!
